gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint3
  gains:
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
tripp_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
  gains:
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1