controller_list:
  - name: fake_test_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - joint3
initial:  # Define initial robot poses per group
  - group: test_arm
    pose: home