test_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - joint1 
    - joint2
    - joint3
#Controller to control end effector joints

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

